version: 0.2
phases:
  install:
    commands:
      - pip3 install -r setup_requirements.txt
  pre_build:
    commands:
      - pip3 install awscli
      - aws configure set region us-east-1
      - aws codeartifact login --tool twine --domain python --domain-owner 608421743782 --repository pythonic-libraries
  build:
    commands:
      - python setup.py sdist --formats=gztar
  post_build:
    commands:
      - twine upload --repository codeartifact dist/fastapi-common-0.3.6.2.tar.gz