version: 0.2
phases:
  install:
    commands:
      - pip3 install -r setup_requirements.txt
  pre_build:
    commands:
      - export var2="value 2"
      - export var3="value 3"
  build:
    commands:
      - pytest -x -v tests/